name: CI Checks
run-name: CI Checks

on:
  push:
    tags: ["v*"]
    branches-ignore: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Get tag name
        id: get_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=dev" >> $GITHUB_ENV
          fi

      - name: Build project
        run: make build/all VERSION=${{ env.VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gocost-binaries
          path: bin/*
          overwrite: "true"
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Downloads
        run: go get -t ./...

      - name: Test
        run: make test

  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gocost-binaries
          path: bin

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_tag.outputs.TAG_NAME }} \
            --title "${{ steps.get_tag.outputs.TAG_NAME }}" \
            --generate-notes \
            bin/gocost-linux-amd64 \
            bin/gocost-windows-amd64.exe \
            bin/gocost-darwin-arm64
